### ISSUE TITLE
Package Not Compatible with R 4.3.1 

### ISSUE THREAD

**Issue by abartolo-912** [tomroh/ecoregions#1]
Looks like this package is no longer compatible as of R 4.3.1... 

GitHub install via devtools fails outright and install.packages gives "package ‘ecoregions’ is not available for this version of R." This is a great package! Any plans to update?

**Comment by tomroh** [comment]
HI @abartolo-912 , this hasn't been published to CRAN. You will have to install via github for use.

**Comment by abartolo-912** [comment]
Hi @tomroh, I do realize that. As of R 4.3.1 installing via github doesn't seem to work. The command 

`devtools::install_github('tomroh/ecoregions', build_vignettes = TRUE)` 

gives this output and error message: 

```
Downloading GitHub repo tomroh/ecoregions@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/tomroh/ecoregions/tarball/HEAD' failed
```
It also fails on a fresh session of R via Posit Cloud, but with a slightly different error message.

**Comment by tomroh** [comment]
That error message from devtools wasn't that helpful I see.

You can use:

```devtools::install_github('tomroh/ecoregions', build_vignettes = FALSE)```

Or install the packages from Suggests in the Description file and you can build the vignettes.

```devtools::install_github('tomroh/ecoregions', build_vignettes = TRUE)```
